Module4 task1
htmlacademy-nodejs/380133-typoteka-3 pull request #10
Opened 2021-03-24 21:41 UTC by IerominSergii

2021-03-25 21:53 UTC, dean992008 requested changes

2021-03-25 21:53 UTC, dean992008 commented on src/service/data-service/category.js
> +      article.сategory.forEach((category) => {
Сейчас падает в этом месте. Ты в `сategory` написал рускую `c`

2021-03-25 21:53 UTC, dean992008 commented on src/service/middlewares/validateArticle.js
> +    const keysExists = ARTICLE_KEYS.every((key) => keys.includes(key));
Не проходит проверку здесь, с валидными ключами. Нужно проверить значения в `ARTICLE_KEYS`.

2021-03-25 21:53 UTC, dean992008 commented on src/service/api/article.js
> +    return res.status(HttpCode.OK).send(createdComment);
В случае успешного создания статьи лучше возвращять статус 201.

2021-03-25 21:53 UTC, dean992008 commented on src/service/api/article.js
> +  router.post(`/:articleId/comments`, (req, res) => {
Нужно добавить проверку валидности полей коментария.

2021-03-25 21:53 UTC, dean992008 commented on src/service/api/article.js
> +    const article = articleService.create(req.body);
Тоже нужно возвращять 201.

2021-03-25 21:53 UTC, dean992008 commented on src/service/api/index.js
> +  const mockData = await getMockData();
Чтение данных лучше будет сделать синхронно. Тут будут проблемы во время написания тестов. Сейчас можно не исправлять, но если столкнешся в следующих задания будешь знать откуда начинать искать.

2021-03-25 21:53 UTC, dean992008 commented on src/service/api/search.js
> +      return res.status(HttpCode.NOT_FOUND).send(ServerMessage.NOT_FOUND_MESSAGE);
Если результат будет пустой не нужно отдавать 404, тольшенство frontend фрейворков восприйму это не корректно. 
В любом случае 200 и результат, даже если это будет пустой массив.

2021-03-25 22:06 UTC, IerominSergii commented on src/service/middlewares/validateArticle.js
> +    const keysExists = ARTICLE_KEYS.every((key) => keys.includes(key));
Проверил, не могу поймать ошибку.
Отправляю тестовый article и он создается:
```
{
    "title": "test title",
    "announce": "test announce",
    "fullText": "test fullText",
    "сategory": ["test сategory"]
}
```

2021-03-26 09:18 UTC, dean992008 commented on src/service/middlewares/validateArticle.js
> +    const keysExists = ARTICLE_KEYS.every((key) => keys.includes(key));
У меня на ключе `сategory` падало. Скорее всего в люче тоде русская буква.

2021-03-26 09:21 UTC, IerominSergii commented on src/service/middlewares/validateArticle.js
> +    const keysExists = ARTICLE_KEYS.every((key) => keys.includes(key));
Видимо да, потому что у меня все окей было, когда я проверял

2021-03-26 09:42 UTC, IerominSergii commented on src/service/data-service/category.js
> +      article.сategory.forEach((category) => {
Исправил

2021-03-26 09:42 UTC, IerominSergii commented on src/service/api/article.js
> +    return res.status(HttpCode.OK).send(createdComment);
Исправил

2021-03-26 09:42 UTC, IerominSergii commented on src/service/api/article.js
> +  router.post(`/:articleId/comments`, (req, res) => {
Добавил

2021-03-26 09:42 UTC, IerominSergii commented on src/service/api/article.js
> +    const article = articleService.create(req.body);
Исправил

2021-03-26 09:43 UTC, IerominSergii commented on src/service/api/index.js
> +  const mockData = await getMockData();
В следующем задание поправлю

2021-03-26 09:43 UTC, IerominSergii commented on src/service/api/search.js
> +      return res.status(HttpCode.NOT_FOUND).send(ServerMessage.NOT_FOUND_MESSAGE);
Возвращаю пустой массив

2021-03-27 18:29 UTC, dean992008 approved these changes

2021-03-27 18:29 UTC, merged