Add article generator
htmlacademy-nodejs/380133-typoteka-3 pull request #3
Opened 2021-03-13 21:07 UTC by IerominSergii

2021-03-14 21:07 UTC, dean992008 requested changes

2021-03-14 21:07 UTC, dean992008 commented on src/service/cli/generate.js
> +const generateTitle = () => TITLES[getRandomInt(0, TITLES.length - 1)];
`getRandomInt(0, ....length - 1)` - Встречается несколько раз. Я бы порекомендовал сделать отдельную утилитарную функцию и использовать ее. Так будет легче читать код и позволит избежать дублей логики. 
P.S. Я имею виду функцию для получения случайного элемента из массива.

2021-03-14 21:07 UTC, dean992008 commented on src/service/cli/generate.js
> +  fs.writeFileSync(FILE_NAME, JSON.stringify(articles));
Использовать `writeFileSync` не хорошая практика. Здесь это допустимо так как операция делается 1 раз, но вообще это крайне плохо, так как она блокирует поток.

2021-03-14 21:07 UTC, dean992008 commented on src/service/cli/generate.js
> +"use strict";
В eslint от аккадемии немного недонастроен, нужно добавить правило `sourceType: 'module'` в `parserOptions:` чтобы он не требовал `use strict`. В nodejs весь код и так выполняется в строгом режиме. 
Добавь это правило и удали везде `use strict`

2021-03-15 07:47 UTC, IerominSergii commented on src/service/cli/generate.js
> +  fs.writeFileSync(FILE_NAME, JSON.stringify(articles));
Да, хорошо, я понял.

У меня возникла сложность с возвратом `ExitCode`.
Если б я использовал `writeFile` с колбэком, то как вернуть `ExitCode ` из `generate(args);`?
(Без async/await и промисов. Т.к., я так понял, в этом задании их еще нельзя использовать)
```
module.exports = {
  name: `--generate`,
  run(args) {
    return generate(args);
  },
};
```

2021-03-15 07:47 UTC, IerominSergii commented on src/service/cli/generate.js
> +const generateTitle = () => TITLES[getRandomInt(0, TITLES.length - 1)];
Добавил утилку

2021-03-15 07:47 UTC, IerominSergii commented on src/service/cli/generate.js
> +"use strict";
Исправил

2021-03-15 08:09 UTC, dean992008 commented on src/service/cli/generate.js
> +  fs.writeFileSync(FILE_NAME, JSON.stringify(articles));
Ты можешь process.exit применить прямо в callback

2021-03-15 08:33 UTC, IerominSergii commented on src/service/cli/generate.js
> +  fs.writeFileSync(FILE_NAME, JSON.stringify(articles));
Поправил

2021-03-15 08:35 UTC, IerominSergii commented on src/service/cli/generate.js
> +  fs.writeFile(FILE_NAME, JSON.stringify(articles), (err) => cb(err));
Тут можно еще упростить?

`fs.writeFile(FILE_NAME, JSON.stringify(articles), (err) => cb(err));`
=>
`fs.writeFile(FILE_NAME, JSON.stringify(articles), cb);`

2021-03-15 08:37 UTC, IerominSergii commented on src/service/cli/generate.js
> +  fs.writeFile(FILE_NAME, JSON.stringify(articles), (err) => cb(err));
упростил

2021-03-15 19:24 UTC, dean992008 approved these changes

2021-03-15 19:25 UTC, merged