Add templates
htmlacademy-nodejs/380133-typoteka-3 pull request #8
Opened 2021-03-20 05:30 UTC by IerominSergii

2021-03-20 21:28 UTC, dean992008 requested changes

2021-03-20 21:28 UTC, dean992008 commented on src/express/templates/components/new-post.pug
> +  section
Скорее всего нужно добавить еще 1 таб, сейчас получается секция на 1 уровне с main, хотя по идее должны быть внутри. 
В других шаблонах также.

2021-03-20 21:28 UTC, dean992008 commented on src/express/templates/pages/main.pug
> +  h1.visually-hidden Главная страница личного блога Типотека
Тоже не хватает отступов. Из-за этого поплыла разметка страницы: http://joxi.ru/EA4vE1EuolWn6m

2021-03-20 21:29 UTC, dean992008 commented
Сорри за задержку. Бы луверен что посмотрел и принял еще днем.

2021-03-21 07:30 UTC, IerominSergii commented on src/express/templates/pages/main.pug
> +  h1.visually-hidden Главная страница личного блога Типотека
Исправил

2021-03-21 07:30 UTC, IerominSergii commented on src/express/templates/components/new-post.pug
> +  section
Исправил

2021-03-21 09:53 UTC, dean992008 approved these changes

2021-03-21 09:53 UTC, merged